baseURL = '/'
languageCode = 'en-us'
title = 'My New Hugo-Bulma Site'

[module]
[[module.imports]]
    disable = false
    ignoreConfig = false
    ignoreImports = false
    path = 'github.com/dindinet/primoStartupVercel'
[[module.imports.mounts]]
    source = '.'
    target = 'static'
